[Encoder]
	Name=embedding

[Decoder]
	Name=bilinear-diag
	RegularizationParameter=0.01

[Shared]
	CodeDimension=500

[Optimizer]
	MaxGradientNorm=1
	ReportTrainLossEvery=10

	[EarlyStopping]
		CheckEvery=10
		BurninPhaseDuration=100

	[Algorithm]
		Name=Adam
		learning_rate=0.1

[General]
	NegativeSampleRate=10
	GraphSplitSize=0.5
	ExperimentName=models/Distmult
	GraphBatchSize=30000

[Evaluation]
	Metric=MRR
